-- ==============================================================================
-- ESQUEMA DE BASE DE DATOS SUPABASE (POSTGRESQL) PARA APP_ALCO
-- Generado por: Agente IA (Antigravity)
-- Fecha: 2026-02-10
--
-- INSTRUCCIONES:
-- 1. Copie todo el contenido de este archivo.
-- 2. Vaya al Dashboard de su proyecto en Supabase -> SQL Editor.
-- 3. Pegue el contenido y haga clic en "Run".
-- ==============================================================================

-- Habilitar extensiones necesarias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- 1. USUARIOS Y PERFILES
-- ==========================================
-- Tabla pública de perfiles (vinculada a auth.users de Supabase)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'calidad', 'produccion', 'logistica', 'ingenieria', 'user')),
    avatar_url TEXT,
    initials TEXT,
    status TEXT DEFAULT 'offline' CHECK (status IN ('online', 'offline', 'busy', 'away')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS para Perfiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- ==========================================
-- 2. GESTIÓN DOCUMENTAL (LIBRARY)
-- ==========================================
CREATE TABLE public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT CHECK (category IN ('Manuales', 'Instructivos', 'Planos', 'Fichas Técnicas', 'Registros')),
    version TEXT DEFAULT 'V1.0',
    status TEXT CHECK (status IN ('Borrador', 'En Revisión', 'Aprobado', 'Obsoleto')) DEFAULT 'Borrador',
    url TEXT, -- Path en Storage
    size TEXT,
    mime_type TEXT,
    author_id UUID REFERENCES public.profiles(id),
    approved_by_id UUID REFERENCES public.profiles(id),
    valid_until DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Documents viewable by authenticated users" ON public.documents FOR SELECT TO authenticated USING (true);
CREATE POLICY "Only QA/Admin can edit documents" ON public.documents FOR ALL TO authenticated USING (
    exists (select 1 from public.profiles where id = auth.uid() and role IN ('admin', 'calidad'))
);

-- ==========================================
-- 3. INSPECCIONES DE CALIDAD
-- ==========================================
CREATE TABLE public.inspections (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    fecha DATE DEFAULT CURRENT_DATE,
    area_proceso TEXT NOT NULL,
    op TEXT NOT NULL,
    plano_opc TEXT,
    diseno_referencia TEXT,
    cant_total INTEGER DEFAULT 0,
    cant_retenida INTEGER DEFAULT 0,
    estado TEXT CHECK (estado IN ('Aprobado', 'Rechazado', 'Pendiente', 'Reprocesar', 'Aprobado (Condicionado)')),
    defecto TEXT DEFAULT 'NINGUNO',
    alert_level TEXT CHECK (alert_level IN ('None', 'Warning', 'Critical')) DEFAULT 'None',
    is_locked BOOLEAN DEFAULT FALSE,
    
    reviso_id UUID REFERENCES public.profiles(id), -- Usuario que inspecciona
    responsable_text TEXT, -- Nombre del operario responsable (campo de texto libre o futuro FK)
    
    accion_correctiva TEXT,
    observacion_sugerida TEXT,
    observacion TEXT,
    photo_url TEXT, -- Path en Storage
    
    ai_metadata JSONB, -- Para guardar datos de análisis IA (confianza, conteo, etc)
    auto_nc_id UUID, -- Link a una No Conformidad si se genera automáticamente
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

ALTER TABLE public.inspections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Inspections viewable by all" ON public.inspections FOR SELECT TO authenticated USING (true);
CREATE POLICY "Inspections insertable by authenticated" ON public.inspections FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Inspections updatable by Creator or QA" ON public.inspections FOR UPDATE TO authenticated USING (
    auth.uid() = created_by OR 
    exists (select 1 from public.profiles where id = auth.uid() and role IN ('admin', 'calidad'))
);

-- ==========================================
-- 4. NO CONFORMIDADES (NC) Y CAPA
-- ==========================================
CREATE TABLE public.non_conformities (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    serial_id TEXT UNIQUE, -- Ej: NC-24-001
    title TEXT NOT NULL,
    process TEXT,
    project TEXT,
    severity TEXT CHECK (severity IN ('Menor', 'Mayor', 'Crítica')),
    status TEXT CHECK (status IN ('Abierta', 'Bajo Análisis', 'CAPA', 'Cerrada', 'Eficaz')) DEFAULT 'Abierta',
    description TEXT,
    rca JSONB, -- 5 Por qués
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE public.nc_actions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    nc_id UUID REFERENCES public.non_conformities(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    responsible TEXT,
    due_date DATE,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.nc_history (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    nc_id UUID REFERENCES public.non_conformities(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id),
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 5. METROLOGÍA: ASIGNACIONES Y PRÉSTAMOS
-- ==========================================
CREATE TABLE public.metrology_assignments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    readable_id TEXT, -- ACTA-timestamp
    fecha DATE DEFAULT CURRENT_DATE,
    area TEXT,
    sede TEXT,
    
    -- Receptor
    receptor_nombre TEXT,
    receptor_cedula TEXT,
    receptor_cargo TEXT,
    
    firma_entrega_url TEXT,
    firma_recibe_url TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_by UUID REFERENCES auth.users(id)
);

CREATE TABLE public.metrology_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id UUID REFERENCES public.metrology_assignments(id) ON DELETE CASCADE,
    equipo_nombre TEXT NOT NULL,
    marca TEXT,
    cantidad INTEGER DEFAULT 1,
    observaciones TEXT
);

-- ==========================================
-- 6. METROLOGÍA: REPOSICIÓN Y BAJA
-- ==========================================
CREATE TABLE public.metrology_replacements (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    fecha_registro DATE DEFAULT CURRENT_DATE,
    
    -- Equipo
    nombre_equipo TEXT NOT NULL,
    marca TEXT,
    codigo TEXT,
    area_uso TEXT,
    
    -- Responsables
    nombre_responsable TEXT,
    nombre_responsable_calidad TEXT,
    
    -- Detalles
    motivo_reposicion TEXT,
    devuelve_equipo_anterior BOOLEAN,
    descripcion_baja TEXT,
    se_cobra_equipo BOOLEAN,
    
    -- Firmas
    firma_responsable_area_url TEXT,
    firma_responsable_calidad_url TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 7. ENLACES EXTERNOS (CONFIGURACIÓN)
-- ==========================================
CREATE TABLE public.external_links (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    color TEXT DEFAULT 'blue',
    created_by UUID REFERENCES auth.users(id)
);

-- ==========================================
-- 8. TRIGGERS PARA UPDATED_AT
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_documents_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ==========================================
-- 9. NOTAS ADICIONALES
-- ==========================================

-- ==============================================================================
-- 10. TRIGGER PARA CREACIÓN AUTOMÁTICA DE PERFILES (IMPORTANTE)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

